[package]
name = "superstate"
version = "0.1.0"
edition = "2024"

[dependencies]
derive_more = { version = "2.1.0", features = ["constructor", "from", "into"] }
either = "1.15.0"

[dev-dependencies]
test-case = "3.3.1"
